kind: Deployment
apiVersion: apps/v1
metadata:
  name: predicted-metric-container-exporter
  namespace: polaris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predicted-metric-container-exporter
  template:
    metadata:
      labels:
        app: predicted-metric-container-exporter
    spec:
      containers:
        - name: exporter
          image: polarissloc/predicted-metric-container-exporter:0.5
          imagePullPolicy: Always
          env:
            - name: TARGET_GVK
              value: "apps/v1/StatefulSet"
            - name: TARGET_NAMESPACE
              value: "demo-mesh"
            - name: RECONCILE_INTERVAL
              value: "5"
            - name: LOG
              value: "DEBUG"
            - name: EXPORTER_PORT
              value: "9877"
          ports:
            - containerPort: 9877
              name: mport
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: predicted-metric-container-exporter
  name: predicted-metric-container-exporter-service
  namespace: polaris
spec:
  selector:
    app: predicted-metric-container-exporter
  ports:
    - name: mport
      port: 9877
      targetPort: 9877
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: polaris
  name: predicted-metric-container-exporter-servicemonitor
  labels:
    app: predicted-metric-container-exporter
    # Needed because of https://github.com/prometheus-operator/prometheus-operator/issues/1470#issuecomment-397500048
    release: prometheus-release-1
spec:
  namespaceSelector:
    matchNames:
      - polaris
  selector:
    matchLabels:
      app: predicted-metric-container-exporter
  endpoints:
    - targetPort: 9877
      interval: 20s
      path: /metrics
