apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: horizontal-elasticity-strat-controller
    tier: control-plane
  name: horizontal-elasticity-strat-controller
  namespace: polaris
spec:
  selector:
    matchLabels:
      component: horizontal-elasticity-strat-controller
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: horizontal-elasticity-strat-controller
        tier: control-plane
    spec:
      serviceAccountName: horizontal-elasticity-strat-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # Ensure that the controller is only scheduled on Intel 64-bit nodes.
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      tolerations:
        # Ensure that the controller can be scheduled on master nodes.
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - image: polarissloc/horizontal-elasticity-strat-controller:latest
          name: elasticity-controller
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          securityContext:
            privileged: false
          env:
            # Workaround for an issue with kubernetes-client when using IPv6 (https://github.com/kubernetes-client/javascript/issues/599)
            - name: KUBERNETES_SERVICE_HOST
              value: kubernetes.default.svc
