apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deployment
  namespace: demo
  labels:
    app: pause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:latest

